name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      keep:
        description: 'Number of latest runs to keep per workflow (default: 1)'
        required: false
        default: '1'

jobs:
  cleanup:
    name: Delete old runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: ${{ github.event.inputs.keep }}
